ol.proj.proj4.register(proj4);
ol.proj.get("EPSG:2193").setExtent([1613706.743694, 5577755.161498, 1837620.635960, 5714012.271021]);
var wms_layers = [];


        var lyr_LINZBasemaps_0 = new ol.layer.Tile({
            'title': 'LINZ Basemaps',
            'type': 'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
    attributions: ' ',
                url: 'https://basemaps.linz.govt.nz/v1/tiles/aerial/WebMercatorQuad/{z}/{x}/{y}.webp?api=c01gdc39mem05atdkbm5ramk8nq'
            })
        });
var format_NZLRILandUseCapability2021_1 = new ol.format.GeoJSON();
var features_NZLRILandUseCapability2021_1 = format_NZLRILandUseCapability2021_1.readFeatures(json_NZLRILandUseCapability2021_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:2193'});
var jsonSource_NZLRILandUseCapability2021_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_NZLRILandUseCapability2021_1.addFeatures(features_NZLRILandUseCapability2021_1);
var lyr_NZLRILandUseCapability2021_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_NZLRILandUseCapability2021_1, 
                style: style_NZLRILandUseCapability2021_1,
                interactive: true,
    title: 'NZLRI Land Use Capability 2021<br />\
    <img src="styles/legend/NZLRILandUseCapability2021_1_0.png" /> 1<br />\
    <img src="styles/legend/NZLRILandUseCapability2021_1_1.png" /> 2<br />\
    <img src="styles/legend/NZLRILandUseCapability2021_1_2.png" /> 3<br />\
    <img src="styles/legend/NZLRILandUseCapability2021_1_3.png" /> <br />'
        });
var format_NPDCHighlyProductiveLandProposedRuralZone_2 = new ol.format.GeoJSON();
var features_NPDCHighlyProductiveLandProposedRuralZone_2 = format_NPDCHighlyProductiveLandProposedRuralZone_2.readFeatures(json_NPDCHighlyProductiveLandProposedRuralZone_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:2193'});
var jsonSource_NPDCHighlyProductiveLandProposedRuralZone_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_NPDCHighlyProductiveLandProposedRuralZone_2.addFeatures(features_NPDCHighlyProductiveLandProposedRuralZone_2);
var lyr_NPDCHighlyProductiveLandProposedRuralZone_2 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_NPDCHighlyProductiveLandProposedRuralZone_2, 
                style: style_NPDCHighlyProductiveLandProposedRuralZone_2,
                interactive: true,
                title: '<img src="styles/legend/NPDCHighlyProductiveLandProposedRuralZone_2.png" /> NPDC - Highly Productive Land - Proposed Rural Zone'
            });
var format_NPDCHighlyProductiveLandOperativeRuralZone_3 = new ol.format.GeoJSON();
var features_NPDCHighlyProductiveLandOperativeRuralZone_3 = format_NPDCHighlyProductiveLandOperativeRuralZone_3.readFeatures(json_NPDCHighlyProductiveLandOperativeRuralZone_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:2193'});
var jsonSource_NPDCHighlyProductiveLandOperativeRuralZone_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_NPDCHighlyProductiveLandOperativeRuralZone_3.addFeatures(features_NPDCHighlyProductiveLandOperativeRuralZone_3);
var lyr_NPDCHighlyProductiveLandOperativeRuralZone_3 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_NPDCHighlyProductiveLandOperativeRuralZone_3, 
                style: style_NPDCHighlyProductiveLandOperativeRuralZone_3,
                interactive: true,
                title: '<img src="styles/legend/NPDCHighlyProductiveLandOperativeRuralZone_3.png" /> NPDC - Highly Productive Land - Operative Rural Zone'
            });

lyr_LINZBasemaps_0.setVisible(true);lyr_NZLRILandUseCapability2021_1.setVisible(true);lyr_NPDCHighlyProductiveLandProposedRuralZone_2.setVisible(false);lyr_NPDCHighlyProductiveLandOperativeRuralZone_3.setVisible(false);
var layersList = [lyr_LINZBasemaps_0,lyr_NZLRILandUseCapability2021_1,lyr_NPDCHighlyProductiveLandProposedRuralZone_2,lyr_NPDCHighlyProductiveLandOperativeRuralZone_3];
lyr_NZLRILandUseCapability2021_1.set('fieldAliases', {'luc': 'luc', 'lcorr': 'lcorr', 'nzcu': 'nzcu', 'type': 'type', 'lcorrclass': 'lcorrclass', 'lcorrlim': 'lcorrlim', 'lcorrunit': 'lcorrunit', 'regname': 'regname', 'rock': 'rock', 'toprock': 'toprock', 'baserock': 'baserock', 'rock2': 'rock2', 'surcode': 'surcode', 'mainsoil': 'mainsoil', 'soil': 'soil', 'nzsc': 'nzsc', 'slope': 'slope', 'erosion': 'erosion', 'veg': 'veg', 'veg2': 'veg2', 'ccav': 'ccav', 'ccto_1': 'ccto_1', 'ccpo': 'ccpo', 'prsir': 'prsir', 'prsic': 'prsic', 'prsiav': 'prsiav', 'edition_1': 'edition_1', 'polyid': 'polyid', 'domluc': 'domluc', 'present_erosion': 'present_erosion', 'potential_erosion': 'potential_erosion', 'origin': 'origin', 'nld_legend': 'nld_legend', 'wko_legend': 'wko_legend', 'cor_legend': 'cor_legend', 'bop_legend': 'bop_legend', 'ebp_legend': 'ebp_legend', 'gec_legend': 'gec_legend', 'nhb_legend': 'nhb_legend', 'shw_legend': 'shw_legend', 'wln_legend': 'wln_legend', 'tmu_legend': 'tmu_legend', 'si_legend': 'si_legend', 'marl_legend': 'marl_legend', 'nzcu_description': 'nzcu_description', 'orig_ni_si_unit_descr': 'orig_ni_si_unit_descr', 'the_geom_Length': 'the_geom_Length', 'the_geom_Area': 'the_geom_Area', });
lyr_NPDCHighlyProductiveLandProposedRuralZone_2.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'Zone': 'Zone', 'Shape__Are': 'Shape__Are', 'Shape__Len': 'Shape__Len', 'luc': 'luc', 'lcorr': 'lcorr', 'nzcu': 'nzcu', 'type': 'type', 'lcorrclass': 'lcorrclass', 'lcorrlim': 'lcorrlim', 'lcorrunit': 'lcorrunit', 'regname': 'regname', 'rock': 'rock', 'toprock': 'toprock', 'baserock': 'baserock', 'rock2': 'rock2', 'surcode': 'surcode', 'mainsoil': 'mainsoil', 'soil': 'soil', 'nzsc': 'nzsc', 'slope': 'slope', 'erosion': 'erosion', 'veg': 'veg', 'veg2': 'veg2', 'ccav': 'ccav', 'ccto_1': 'ccto_1', 'ccpo': 'ccpo', 'prsir': 'prsir', 'prsic': 'prsic', 'prsiav': 'prsiav', 'edition_1': 'edition_1', 'polyid': 'polyid', 'domluc': 'domluc', 'present_er': 'present_er', 'potential_': 'potential_', 'origin': 'origin', 'nld_legend': 'nld_legend', 'wko_legend': 'wko_legend', 'cor_legend': 'cor_legend', 'bop_legend': 'bop_legend', 'ebp_legend': 'ebp_legend', 'gec_legend': 'gec_legend', 'nhb_legend': 'nhb_legend', 'shw_legend': 'shw_legend', 'wln_legend': 'wln_legend', 'tmu_legend': 'tmu_legend', 'si_legend': 'si_legend', 'marl_legen': 'marl_legen', 'nzcu_descr': 'nzcu_descr', 'orig_ni_si': 'orig_ni_si', 'the_geom_L': 'the_geom_L', 'the_geom_A': 'the_geom_A', });
lyr_NPDCHighlyProductiveLandOperativeRuralZone_3.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'Zone': 'Zone', 'Type': 'Type', 'Status': 'Status', 'BlueprintK': 'BlueprintK', 'Creator': 'Creator', 'DateCreate': 'DateCreate', 'Editor': 'Editor', 'DateEdited': 'DateEdited', 'ZoneType': 'ZoneType', 'ZoneClass': 'ZoneClass', 'SHAPE.STAr': 'SHAPE.STAr', 'SHAPE.STLe': 'SHAPE.STLe', 'luc': 'luc', 'lcorr': 'lcorr', 'nzcu': 'nzcu', 'type_1': 'type_1', 'lcorrclass': 'lcorrclass', 'lcorrlim': 'lcorrlim', 'lcorrunit': 'lcorrunit', 'regname': 'regname', 'rock': 'rock', 'toprock': 'toprock', 'baserock': 'baserock', 'rock2': 'rock2', 'surcode': 'surcode', 'mainsoil': 'mainsoil', 'soil': 'soil', 'nzsc': 'nzsc', 'slope': 'slope', 'erosion': 'erosion', 'veg': 'veg', 'veg2': 'veg2', 'ccav': 'ccav', 'ccto_1': 'ccto_1', 'ccpo': 'ccpo', 'prsir': 'prsir', 'prsic': 'prsic', 'prsiav': 'prsiav', 'edition_1': 'edition_1', 'polyid': 'polyid', 'domluc': 'domluc', 'present_er': 'present_er', 'potential_': 'potential_', 'origin': 'origin', 'nld_legend': 'nld_legend', 'wko_legend': 'wko_legend', 'cor_legend': 'cor_legend', 'bop_legend': 'bop_legend', 'ebp_legend': 'ebp_legend', 'gec_legend': 'gec_legend', 'nhb_legend': 'nhb_legend', 'shw_legend': 'shw_legend', 'wln_legend': 'wln_legend', 'tmu_legend': 'tmu_legend', 'si_legend': 'si_legend', 'marl_legen': 'marl_legen', 'nzcu_descr': 'nzcu_descr', 'orig_ni_si': 'orig_ni_si', 'the_geom_L': 'the_geom_L', 'the_geom_A': 'the_geom_A', });
lyr_NZLRILandUseCapability2021_1.set('fieldImages', {'luc': 'TextEdit', 'lcorr': 'TextEdit', 'nzcu': 'TextEdit', 'type': 'TextEdit', 'lcorrclass': 'Range', 'lcorrlim': 'TextEdit', 'lcorrunit': 'Range', 'regname': 'TextEdit', 'rock': 'TextEdit', 'toprock': 'TextEdit', 'baserock': 'TextEdit', 'rock2': 'TextEdit', 'surcode': 'TextEdit', 'mainsoil': 'TextEdit', 'soil': 'TextEdit', 'nzsc': 'TextEdit', 'slope': 'TextEdit', 'erosion': 'TextEdit', 'veg': 'TextEdit', 'veg2': 'TextEdit', 'ccav': 'TextEdit', 'ccto_1': 'TextEdit', 'ccpo': 'TextEdit', 'prsir': 'TextEdit', 'prsic': 'TextEdit', 'prsiav': 'Range', 'edition_1': 'TextEdit', 'polyid': 'Range', 'domluc': 'TextEdit', 'present_erosion': 'TextEdit', 'potential_erosion': 'TextEdit', 'origin': 'TextEdit', 'nld_legend': 'TextEdit', 'wko_legend': 'TextEdit', 'cor_legend': 'TextEdit', 'bop_legend': 'TextEdit', 'ebp_legend': 'TextEdit', 'gec_legend': 'TextEdit', 'nhb_legend': 'TextEdit', 'shw_legend': 'TextEdit', 'wln_legend': 'TextEdit', 'tmu_legend': 'TextEdit', 'si_legend': 'TextEdit', 'marl_legend': 'TextEdit', 'nzcu_description': 'TextEdit', 'orig_ni_si_unit_descr': 'TextEdit', 'the_geom_Length': 'TextEdit', 'the_geom_Area': 'TextEdit', });
lyr_NPDCHighlyProductiveLandProposedRuralZone_2.set('fieldImages', {'OBJECTID': 'TextEdit', 'Zone': 'TextEdit', 'Shape__Are': 'TextEdit', 'Shape__Len': 'TextEdit', 'luc': 'TextEdit', 'lcorr': 'TextEdit', 'nzcu': 'TextEdit', 'type': 'TextEdit', 'lcorrclass': 'TextEdit', 'lcorrlim': 'TextEdit', 'lcorrunit': 'TextEdit', 'regname': 'TextEdit', 'rock': 'TextEdit', 'toprock': 'TextEdit', 'baserock': 'TextEdit', 'rock2': 'TextEdit', 'surcode': 'TextEdit', 'mainsoil': 'TextEdit', 'soil': 'TextEdit', 'nzsc': 'TextEdit', 'slope': 'TextEdit', 'erosion': 'TextEdit', 'veg': 'TextEdit', 'veg2': 'TextEdit', 'ccav': 'TextEdit', 'ccto_1': 'TextEdit', 'ccpo': 'TextEdit', 'prsir': 'TextEdit', 'prsic': 'TextEdit', 'prsiav': 'TextEdit', 'edition_1': 'TextEdit', 'polyid': 'TextEdit', 'domluc': 'TextEdit', 'present_er': 'TextEdit', 'potential_': 'TextEdit', 'origin': 'TextEdit', 'nld_legend': 'TextEdit', 'wko_legend': 'TextEdit', 'cor_legend': 'TextEdit', 'bop_legend': 'TextEdit', 'ebp_legend': 'TextEdit', 'gec_legend': 'TextEdit', 'nhb_legend': 'TextEdit', 'shw_legend': 'TextEdit', 'wln_legend': 'TextEdit', 'tmu_legend': 'TextEdit', 'si_legend': 'TextEdit', 'marl_legen': 'TextEdit', 'nzcu_descr': 'TextEdit', 'orig_ni_si': 'TextEdit', 'the_geom_L': 'TextEdit', 'the_geom_A': 'TextEdit', });
lyr_NPDCHighlyProductiveLandOperativeRuralZone_3.set('fieldImages', {'OBJECTID': 'TextEdit', 'Zone': 'TextEdit', 'Type': 'TextEdit', 'Status': 'TextEdit', 'BlueprintK': 'TextEdit', 'Creator': 'TextEdit', 'DateCreate': 'TextEdit', 'Editor': 'TextEdit', 'DateEdited': 'TextEdit', 'ZoneType': 'TextEdit', 'ZoneClass': 'TextEdit', 'SHAPE.STAr': 'TextEdit', 'SHAPE.STLe': 'TextEdit', 'luc': 'TextEdit', 'lcorr': 'TextEdit', 'nzcu': 'TextEdit', 'type_1': 'TextEdit', 'lcorrclass': 'TextEdit', 'lcorrlim': 'TextEdit', 'lcorrunit': 'TextEdit', 'regname': 'TextEdit', 'rock': 'TextEdit', 'toprock': 'TextEdit', 'baserock': 'TextEdit', 'rock2': 'TextEdit', 'surcode': 'TextEdit', 'mainsoil': 'TextEdit', 'soil': 'TextEdit', 'nzsc': 'TextEdit', 'slope': 'TextEdit', 'erosion': 'TextEdit', 'veg': 'TextEdit', 'veg2': 'TextEdit', 'ccav': 'TextEdit', 'ccto_1': 'TextEdit', 'ccpo': 'TextEdit', 'prsir': 'TextEdit', 'prsic': 'TextEdit', 'prsiav': 'TextEdit', 'edition_1': 'TextEdit', 'polyid': 'TextEdit', 'domluc': 'TextEdit', 'present_er': 'TextEdit', 'potential_': 'TextEdit', 'origin': 'TextEdit', 'nld_legend': 'TextEdit', 'wko_legend': 'TextEdit', 'cor_legend': 'TextEdit', 'bop_legend': 'TextEdit', 'ebp_legend': 'TextEdit', 'gec_legend': 'TextEdit', 'nhb_legend': 'TextEdit', 'shw_legend': 'TextEdit', 'wln_legend': 'TextEdit', 'tmu_legend': 'TextEdit', 'si_legend': 'TextEdit', 'marl_legen': 'TextEdit', 'nzcu_descr': 'TextEdit', 'orig_ni_si': 'TextEdit', 'the_geom_L': 'TextEdit', 'the_geom_A': 'TextEdit', });
lyr_NZLRILandUseCapability2021_1.set('fieldLabels', {'luc': 'inline label', 'lcorr': 'inline label', 'nzcu': 'inline label', 'type': 'inline label', 'lcorrclass': 'inline label', 'lcorrlim': 'inline label', 'lcorrunit': 'inline label', 'regname': 'inline label', 'rock': 'inline label', 'toprock': 'inline label', 'baserock': 'inline label', 'rock2': 'inline label', 'surcode': 'inline label', 'mainsoil': 'inline label', 'soil': 'inline label', 'nzsc': 'inline label', 'slope': 'inline label', 'erosion': 'inline label', 'veg': 'inline label', 'veg2': 'inline label', 'ccav': 'inline label', 'ccto_1': 'inline label', 'ccpo': 'inline label', 'prsir': 'inline label', 'prsic': 'inline label', 'prsiav': 'inline label', 'edition_1': 'inline label', 'polyid': 'inline label', 'domluc': 'inline label', 'present_erosion': 'inline label', 'potential_erosion': 'inline label', 'origin': 'inline label', 'nld_legend': 'inline label', 'wko_legend': 'inline label', 'cor_legend': 'inline label', 'bop_legend': 'inline label', 'ebp_legend': 'inline label', 'gec_legend': 'inline label', 'nhb_legend': 'inline label', 'shw_legend': 'inline label', 'wln_legend': 'inline label', 'tmu_legend': 'inline label', 'si_legend': 'inline label', 'marl_legend': 'inline label', 'nzcu_description': 'inline label', 'orig_ni_si_unit_descr': 'inline label', 'the_geom_Length': 'inline label', 'the_geom_Area': 'inline label', });
lyr_NPDCHighlyProductiveLandProposedRuralZone_2.set('fieldLabels', {'OBJECTID': 'inline label', 'Zone': 'inline label', 'Shape__Are': 'inline label', 'Shape__Len': 'inline label', 'luc': 'inline label', 'lcorr': 'inline label', 'nzcu': 'inline label', 'type': 'inline label', 'lcorrclass': 'inline label', 'lcorrlim': 'inline label', 'lcorrunit': 'inline label', 'regname': 'inline label', 'rock': 'inline label', 'toprock': 'inline label', 'baserock': 'inline label', 'rock2': 'inline label', 'surcode': 'inline label', 'mainsoil': 'inline label', 'soil': 'inline label', 'nzsc': 'inline label', 'slope': 'inline label', 'erosion': 'inline label', 'veg': 'inline label', 'veg2': 'inline label', 'ccav': 'inline label', 'ccto_1': 'inline label', 'ccpo': 'inline label', 'prsir': 'inline label', 'prsic': 'inline label', 'prsiav': 'inline label', 'edition_1': 'inline label', 'polyid': 'inline label', 'domluc': 'inline label', 'present_er': 'inline label', 'potential_': 'inline label', 'origin': 'inline label', 'nld_legend': 'inline label', 'wko_legend': 'inline label', 'cor_legend': 'inline label', 'bop_legend': 'inline label', 'ebp_legend': 'inline label', 'gec_legend': 'inline label', 'nhb_legend': 'inline label', 'shw_legend': 'inline label', 'wln_legend': 'inline label', 'tmu_legend': 'inline label', 'si_legend': 'inline label', 'marl_legen': 'inline label', 'nzcu_descr': 'inline label', 'orig_ni_si': 'inline label', 'the_geom_L': 'inline label', 'the_geom_A': 'inline label', });
lyr_NPDCHighlyProductiveLandOperativeRuralZone_3.set('fieldLabels', {'OBJECTID': 'inline label', 'Zone': 'inline label', 'Type': 'inline label', 'Status': 'inline label', 'BlueprintK': 'inline label', 'Creator': 'inline label', 'DateCreate': 'inline label', 'Editor': 'inline label', 'DateEdited': 'inline label', 'ZoneType': 'inline label', 'ZoneClass': 'inline label', 'SHAPE.STAr': 'inline label', 'SHAPE.STLe': 'inline label', 'luc': 'inline label', 'lcorr': 'inline label', 'nzcu': 'inline label', 'type_1': 'inline label', 'lcorrclass': 'inline label', 'lcorrlim': 'inline label', 'lcorrunit': 'inline label', 'regname': 'inline label', 'rock': 'inline label', 'toprock': 'inline label', 'baserock': 'inline label', 'rock2': 'inline label', 'surcode': 'inline label', 'mainsoil': 'inline label', 'soil': 'inline label', 'nzsc': 'inline label', 'slope': 'inline label', 'erosion': 'inline label', 'veg': 'inline label', 'veg2': 'inline label', 'ccav': 'inline label', 'ccto_1': 'inline label', 'ccpo': 'inline label', 'prsir': 'inline label', 'prsic': 'inline label', 'prsiav': 'inline label', 'edition_1': 'inline label', 'polyid': 'inline label', 'domluc': 'inline label', 'present_er': 'inline label', 'potential_': 'inline label', 'origin': 'inline label', 'nld_legend': 'inline label', 'wko_legend': 'inline label', 'cor_legend': 'inline label', 'bop_legend': 'inline label', 'ebp_legend': 'inline label', 'gec_legend': 'inline label', 'nhb_legend': 'inline label', 'shw_legend': 'inline label', 'wln_legend': 'inline label', 'tmu_legend': 'inline label', 'si_legend': 'inline label', 'marl_legen': 'inline label', 'nzcu_descr': 'inline label', 'orig_ni_si': 'inline label', 'the_geom_L': 'inline label', 'the_geom_A': 'inline label', });
lyr_NPDCHighlyProductiveLandOperativeRuralZone_3.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});